### ISSUE TITLE
Convenient way of typing strings with symbols like underscore?

### ISSUE THREAD

**Issue by murlakatamenka** [autopilot-rs/autopilot-rs#22]
Hi, is there a convenient way of typing strings with symbols like underscore?

### Reasoning

```rust
use autopylot::key;

key::type_string("test_subject", &[], 0., 0.);
```

will type `test-subject` instead of desired `test_subject`.

### Current workaround

```rust
use autopylot::key;

key::type_string("test", &[], 0., 0.);
key::type_string("-", &[key::Flag::Shift], 0., 0.); // or "_"
key::type_string("test", &[], 0., 0.);
```

isn't very convenient but does the job done.

Probably I'm missing something? Using Linux here.

P.S. Thanks for the crate <3

**Comment by msanders** [comment]
It looks like the hyphen is missing from [this list](https://github.com/autopilot-rs/autopilot-rs/blob/9806fa2dcca01be82e003d1f1c4df1e207eba557/src/key.rs#L221). Adding that constant should fix the issue. If you're interested, please put up a PR - otherwise I'll add it sometime tomorrow.

If anyone knows of a better way to go about this on Linux / X11, I'm interested to hear that as well.

**Comment by murlakatamenka** [comment]
Thanks, I'll send PR. I see semicolon `':'` is used twice in that list, I'll replace it with underscore `'_'`
